# Generated by Django 4.2.5 on 2023-12-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
