# Generated by Django 4.2.7 on 2024-01-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_followerscount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerscount',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
