# Generated by Django 4.2.7 on 2024-01-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forget_password_token',
        ),
    ]
