# Generated by Django 4.2.7 on 2024-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profile_forget_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_username', models.CharField(max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
